# ---------------------------------------------------------
# Gruvbox Material Color Scheme 
# ---------------------------------------------------------

# Foreground and Background
foreground           #d4be98
background           #1d2021

# Selection
selection_foreground #d4be98
selection_background #504945

# Cursor
cursor               #d4be98
cursor_text_color    #1d2021

# ---------------------------------------------------------
# 16 Standard Colors
# ---------------------------------------------------------

# Black
color0  #282828
color8  #928374

# Red
color1  #ea6962
color9  #ea6962

# Green
color2  #a9b665
color10 #a9b665

# Yellow
color3  #d8a657
color11 #d8a657

# Blue
color4  #7daeA3
color12 #7daeA3

# Magenta (Purple)
color5  #d3869b
color13 #d3869b

# Cyan (Aqua)
color6  #89b482
color14 #89d482

# White
color7  #d4be98
color15 #ddc7a1
